# Generated by Django 3.0.14 on 2021-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=1, help_text='Email Address', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
